version: "3"

services:
  db:
    container_name: postgres_test_2
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    env_file:
      - ./.env

  web:
    container_name: test_projectt
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./media/:/media
      - ./static/:/static
      - ./:/app
    entrypoint: ./wsgi-entrypoint.sh
    networks:
      - my_network
    depends_on:
      - db

volumes:
  media:
  static:
  postgres_data:

networks:
  my_network: