# Generated by Django 3.2.7 on 2023-02-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('name', models.CharField(max_length=127, verbose_name='название')),
                ('location', models.CharField(max_length=127, verbose_name='локация')),
                ('image', models.ImageField(upload_to='event/images/', verbose_name='kartina')),
                ('description', models.TextField(verbose_name='Opisaniye')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='company.company', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
