# Generated by Django 3.2.7 on 2023-02-13 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Nazvaniye')),
                ('video', models.FileField(upload_to='video/video/', verbose_name='video')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(verbose_name='Opisaniye')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='company.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
